default_platform(:ios)

platform :ios do
  desc "Build iOS app"
  lane :beta do
    build_app(
      workspace: ENV["IOS_WORKSPACE"] || "ios/App.xcworkspace",
      scheme: ENV["IOS_SCHEME"] || "App"
    )
  end
  desc "Upload to TestFlight"
  lane :testflight do
    build_app(
      workspace: ENV["IOS_WORKSPACE"] || "ios/App.xcworkspace",
      scheme: ENV["IOS_SCHEME"] || "App"
    )
    upload_to_testflight
  end
end
